const calcBtn = document.getElementById('calcBtn');
const status = document.getElementById('status');
const resultGrid = document.getElementById('resultGrid');

/**
 * Minecraft BE ダメージシミュレーション (32bit float 厳密再現)
  */
  function simulate(baseAtk, strLv, wkWv, isCrit) {
      let current = Math.fround(baseAtk);

          // 1. 攻撃力上昇 (Strength)
              const strMult = Math.fround(1.3);
                  const strPlus = Math.fround(1.0);
                      // Level 0で1回、Level 255で256回反復
                          for (let i = 0; i <= strLv; i++) {
                                  current = Math.fround(current * strMult);
                                          current = Math.fround(current + strPlus);
                                              }

                                                  // 2. 弱体化 (Weakness)
                                                      const wkMult = Math.fround(0.8);
                                                          const wkMinus = Math.fround(0.5);
                                                              // Level 0で1回、Level 255で256回反復
                                                                  for (let i = 0; i <= wkWv; i++) {
                                                                          current = Math.fround(current * wkMult - wkMinus);
                                                                              }

                                                                                  // 3. クリティカルヒット (最後に計算)
                                                                                      if (isCrit) {
                                                                                              current = Math.fround(current * Math.fround(1.5));
                                                                                                  }

                                                                                                      return current;
                                                                                                      }

                                                                                                      /**
                                                                                                       * 計算実行イベント
                                                                                                        */
                                                                                                        calcBtn.addEventListener('click', () => {
                                                                                                            const baseAtk = parseFloat(document.getElementById('baseAtk').value) || 0;
                                                                                                                const target = parseFloat(document.getElementById('targetDmg').value) || 0;
                                                                                                                    const isCrit = document.getElementById('isCritical').checked;

                                                                                                                        calcBtn.disabled = true;
                                                                                                                            status.innerText = "65,536パターンを走査中...";

                                                                                                                                // UIの描画更新を妨げないようにsetTimeoutを使用
                                                                                                                                    setTimeout(() => {
                                                                                                                                            // パターン1: 目標に最も近い数値 (絶対誤差)
                                                                                                                                                    let p1BestDiff = Infinity;
                                                                                                                                                            let p1Res = 0, p1Str = 0, p1Wk = 0;

                                                                                                                                                                    // パターン2: 目標以上で最も近い数値
                                                                                                                                                                            let p2BestDiff = Infinity;
                                                                                                                                                                                    let p2Res = 0, p2Str = 0, p2Wk = 0;

                                                                                                                                                                                            for (let s = 0; s <= 255; s++) {
                                                                                                                                                                                                        for (let w = 0; w <= 255; w++) {
                                                                                                                                                                                                                        const res = simulate(baseAtk, s, w, isCrit);
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        // パターン1の更新
                                                                                                                                                                                                                                                                        const diff1 = Math.abs(res - target);
                                                                                                                                                                                                                                                                                        if (diff1 < p1BestDiff) {
                                                                                                                                                                                                                                                                                                            p1BestDiff = diff1;
                                                                                                                                                                                                                                                                                                                                p1Res = res;
                                                                                                                                                                                                                                                                                                                                                    p1Str = s;
                                                                                                                                                                                                                                                                                                                                                                        p1Wk = w;
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        // パターン2の更新
                                                                                                                                                                                                                                                                                                                                                                                                                        if (res >= target) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            const diff2 = res - target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (diff2 < p2BestDiff) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        p2BestDiff = diff2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                p2Res = res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        p2Str = s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                p2Wk = w;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 表示結果の更新
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        displayResult('p1', p1Res, p1Str, p1Wk, target);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (p2BestDiff === Infinity) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('p2_val').innerText = "到達不可";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('p2_err').innerText = "-";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            displayResult('p2', p2Res, p2Str, p2Wk, target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resultGrid.style.display = 'grid';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status.innerText = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            calcBtn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 各カードに結果を反映する関数
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function displayResult(prefix, val, str, wk, target) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const diff = val - target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const diffSign = diff >= 0 ? "+" : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById(`${prefix}_val`).innerText = val.toLocaleString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById(`${prefix}_err`).innerText = `誤差: ${diffSign}${diff.toLocaleString()}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.getElementById(`${prefix}_str`).innerText = str;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById(`${prefix}_wk`).innerText = wk;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }